package com.one.pos.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.one.pos.db.ItemType;
import com.one.pos.db.Item;

import com.one.pos.db.greendao.ItemTypeDao;
import com.one.pos.db.greendao.ItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemTypeDaoConfig;
    private final DaoConfig itemDaoConfig;

    private final ItemTypeDao itemTypeDao;
    private final ItemDao itemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemTypeDaoConfig = daoConfigMap.get(ItemTypeDao.class).clone();
        itemTypeDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        itemTypeDao = new ItemTypeDao(itemTypeDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);

        registerDao(ItemType.class, itemTypeDao);
        registerDao(Item.class, itemDao);
    }
    
    public void clear() {
        itemTypeDaoConfig.clearIdentityScope();
        itemDaoConfig.clearIdentityScope();
    }

    public ItemTypeDao getItemTypeDao() {
        return itemTypeDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

}
