package com.gzdb.basepos.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gzdb.supermarket.been.GoodUnitBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GOOD_UNIT_BEAN".
*/
public class GoodUnitBeanDao extends AbstractDao<GoodUnitBean, Long> {

    public static final String TABLENAME = "GOOD_UNIT_BEAN";

    /**
     * Properties of entity GoodUnitBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AutoID = new Property(0, Long.class, "autoID", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Status = new Property(3, int.class, "status", false, "STATUS");
    }


    public GoodUnitBeanDao(DaoConfig config) {
        super(config);
    }
    
    public GoodUnitBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GOOD_UNIT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: autoID
                "\"ID\" TEXT UNIQUE ," + // 1: id
                "\"TITLE\" TEXT," + // 2: title
                "\"STATUS\" INTEGER NOT NULL );"); // 3: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GOOD_UNIT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GoodUnitBean entity) {
        stmt.clearBindings();
 
        Long autoID = entity.getAutoID();
        if (autoID != null) {
            stmt.bindLong(1, autoID);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GoodUnitBean entity) {
        stmt.clearBindings();
 
        Long autoID = entity.getAutoID();
        if (autoID != null) {
            stmt.bindLong(1, autoID);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
        stmt.bindLong(4, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GoodUnitBean readEntity(Cursor cursor, int offset) {
        GoodUnitBean entity = new GoodUnitBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // autoID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.getInt(offset + 3) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GoodUnitBean entity, int offset) {
        entity.setAutoID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStatus(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GoodUnitBean entity, long rowId) {
        entity.setAutoID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GoodUnitBean entity) {
        if(entity != null) {
            return entity.getAutoID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GoodUnitBean entity) {
        return entity.getAutoID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
